travis:
  secure:
    BINSTAR_TOKEN: cXRRyVlbmG3ahHcBb/hhZni5CZ2cyjircrU2EL+hne+c5k0/cZ4RHhl7ydDze0UL8QQZZk65ECiDOErXbAdiGTktb0ov+ZFfbngaJxEs+i3cfGwoEgLGDuyVRWUCd4P1H3b5CibzfoiZRM1KErIEhMo4O3nUzLM3aqAcKchobtTK23J4Xw9lMFXMsg7GJD1TD/L7jHL86iWrugmp3obLh/+XubFEymIN2twKB3k1Y6e+GCRWahc+04iK6HICvVwTLuxc9oATzsvfIJSfGtWna99jCMTrjc/Qg+PYPPKGw5A4tzvoGQXtI4z4tRkoN/FhqeaULk8XPMar2i7rcEQPMO6J9pg+eMCDFgfH7M1jww8UAKNdLVYdTUlnWCbz8fXjoBEFt8034Poh/77i/kQ1C02TFNi6FiC9TBjvZnudzjGoBz+AcW03iSQ2E0smS/a/7xCKUhM/EYyzvUhwJ3KgQQy5TmWYJf11+gebgQRuACW+XnZiqOhac9IZ0s/VFnVhpQ2F+Cah1488VgSaJx1ua7/g4LgbHxWWPlnDtJ3M2zUKHsSTFdJPz2XtlH4o4ODDv9Qm048FpexkwppBIQOszMKFTpVfV2y07Idnt16gQbqF7j6VR7OqJMLW+6BkQzFa6UGsL2pxbZHV3I4x2FjKvAbfkzU9KEw2Kztrwzi82Tk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
